-- CREATE

CREATE TABLE department (
                            id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            city            VARCHAR(150)  NOT NULL,
                            district        VARCHAR(150)  NOT NULL,
                            address         VARCHAR(150)  NOT NULL,
                            phone_number    VARCHAR(150)  NOT NULL
);

CREATE TABLE speciality (
                            id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name            VARCHAR(60)   NOT NULL
);

CREATE TABLE doctor (
                            id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name            VARCHAR(100) NOT NULL,
                            birthdate       DATE         NOT NULL,
                            gender          VARCHAR(10)  NOT NULL,
                            speciality_id   BIGINT       REFERENCES speciality (id),
                            works_from_year DATE         NOT NULL,
                            phone_number    VARCHAR(11)  NOT NULL,
                            password        VARCHAR(60)  NOT NULL
);

CREATE TABLE patient (
                         id              BIGINT        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                         birthdate       DATE          NOT NULL,
                         gender          VARCHAR(15)   NOT NULL,
                         chi_policy      VARCHAR(255)  NOT NULL,
                         passport        VARCHAR(15)   NOT NULL,
                         phone_number    VARCHAR(15)   NOT NULL,
                         password        VARCHAR(255)  NOT NULL
);

create table schedule (
                        id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        doctor_id         BIGINT       NOT NULL REFERENCES doctor(id) on DELETE cascade ON UPDATE CASCADE,
                        department_id     BIGINT       NOT NULL REFERENCES department(id) on DELETE cascade ON UPDATE CASCADE,
                        date              DATE         NOT NULL,
                        start_time        TIME         NOT NULL,
                        end_time          TIME         NOT NULL CHECK( end_time > start_time ),
                        cabinet           INT          NOT NULL CHECK( cabinet > 0 ),
                        is_available      BOOLEAN      NOT NULL
);

CREATE TABLE IF NOT EXISTS appointment (
                        id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        patient_id        BIGINT,      FOREIGN KEY (patient_id) REFERENCES patient (Id),
                        doctor_id         BIGINT,      FOREIGN KEY (doctor_id) REFERENCES doctor (Id),
                        date              DATE         NOT NULL,
                        start_time        TIME         NOT NULL
);

-- INSERT

INSERT INTO department(city, district, address, phone_number)
VALUES ('Москва', 'Центральный', 'Красная площадь 15', '+78005553535'),
       ('Санкт-Петербург', 'Калининский', 'Чекистов 28', '+78005553536'),
       ('Волгоград', 'Южный', 'Чапаева 15', '+78005553537'),
       ('Смоленск', 'Октябрьский', 'Кирпичная 25', '+78005553538'),
       ('Сочи', 'Северный', 'Столичная 55', '+78005553539');

INSERT INTO speciality(name)
VALUES ('Хирург'),
       ('Терапевт'),
       ('Офтальмолог'),
       ('Отолоринголог'),
       ('Уролог'),
       ('Гинеколог'),
       ('Эндокринолог'),
       ('Психолог'),
       ('Стоматолог'),
       ('Инфекционист');

INSERT INTO doctor
VALUES  (1, 'Гальцева Ирина Владимировна', '1987-05-12', 'жен', 1, '2000-05-12', '89523997489', 'pass'),
        (2, 'Виноградова Ольга Юрьевна', '1990-09-02', 'жен', 1, '2001-05-12', '89993997989', 'pass'),
        (3, 'Рюмин Алексей Борисович', '1970-11-11', 'муж', 1, '2002-05-12', '89083990010', 'pass'),
        (4, 'Арсланов Рафис Махмутович', '1982-04-04', 'муж', 2, '2001-08-12', '89083046713', 'pass'),
        (5, 'Шмелев Игорь Владимирович', '1991-04-08', 'муж', 2, '2000-04-15', '89045247722', 'pass'),
        (6, 'Екимова Екатерина Алексеевна', '1979-07-29', 'жен', 3, '2002-08-11', '89996996690', 'pass'),
        (7, 'Абаева Раксана Отаровна', '1990-01-22', 'жен', 3, '2001-03-22', '89991034434', 'pass'),
        (8, 'Смирнов Николай Степанович', '1968-10-04', 'муж', 4, '2000-12-14', '89045365417', 'pass'),
        (9, 'Архипова Светлана Измаиловна', '1982-10-30', 'жен', 4, '2002-12-23', '89040882020', 'pass'),
        (10, 'Смирнов Алексей Николаевич', '1995-12-23', 'муж', 5, '2001-01-25', '89993993950', 'pass');

--changeset Anton K:2

ALTER TABLE patient
ADD CONSTRAINT uniq_phone_number UNIQUE (phone_number);

ALTER TABLE patient
ADD COLUMN name VARCHAR(255);


